In [9]:
# PANDAS : (19/09/24)

In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv('Lungcancer.csv')
print(data)

     GENDER  AGE SMOKING YELLOW_FINGERS ANXIETY PEER_PRESSURE CHRONIC_DISEASE  \
0         M   65     Yes            Yes     Yes            No              No
1         F   55     Yes             No      No           Yes             Yes
2         F   78      No             No     Yes           Yes             Yes
3         M   60      No            Yes     Yes           Yes              No
4         F   80     Yes            Yes      No           Yes             Yes
...     ...  ...     ...            ...     ...           ...             ...
2995      F   71      No            Yes     Yes            No              No
2996      F   75     Yes             No     Yes           Yes             Yes
2997      F   62      No             No      No           Yes              No
2998      M   30     Yes            Yes      No            No              No
2999      M   40     Yes             No      No           Yes             Yes

     FATIGUE ALLERGY WHEEZING ALCOHOL_CONSUMING COUGHING SHORTNESS_OF_BREATH  \
0        Yes      No       No                No       No                  No
1         No      No       No               Yes      Yes                 Yes
2         No     Yes       No               Yes      Yes                  No
3        Yes      No      Yes               Yes       No                 Yes
4         No     Yes       No               Yes      Yes                 Yes
...      ...     ...      ...               ...      ...                 ...
2995     Yes     Yes      Yes               Yes       No                 Yes
2996      No      No       No                No      Yes                 Yes
2997      No      No       No               Yes      Yes                  No
2998      No      No       No                No      Yes                  No
2999     Yes      No       No                No      Yes                 Yes

     SWALLOWING_DIFFICULTY CHEST_PAIN LUNG_CANCER
0                       No        Yes          NO
1                       No         No          NO
2                      Yes        Yes         YES
3                       No         No         YES
4                      Yes         No          NO
...                    ...        ...         ...
2995                   Yes         No          NO
2996                    No        Yes          NO
2997                    No         No         YES
2998                   Yes         No         YES
2999                   Yes        Yes         YES

[3000 rows x 16 columns]

In [3]:
data.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,Yes,Yes,Yes,No,No,Yes,No,No,No,No,No,No,Yes,NO
1,F,55,Yes,No,No,Yes,Yes,No,No,No,Yes,Yes,Yes,No,No,NO
2,F,78,No,No,Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,Yes,Yes,YES
3,M,60,No,Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,Yes,No,No,YES
4,F,80,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes,Yes,Yes,No,NO

In [4]:
data.tail()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
2995,F,71,No,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,Yes,Yes,No,NO
2996,F,75,Yes,No,Yes,Yes,Yes,No,No,No,No,Yes,Yes,No,Yes,NO
2997,F,62,No,No,No,Yes,No,No,No,No,Yes,Yes,No,No,No,YES
2998,M,30,Yes,Yes,No,No,No,No,No,No,No,Yes,No,Yes,No,YES
2999,M,40,Yes,No,No,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes,Yes,YES

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 3000 non-null   object
 1   AGE                    3000 non-null   int64
 2   SMOKING                3000 non-null   object
 3   YELLOW_FINGERS         3000 non-null   object
 4   ANXIETY                3000 non-null   object
 5   PEER_PRESSURE          3000 non-null   object
 6   CHRONIC_DISEASE        3000 non-null   object
 7   FATIGUE                3000 non-null   object
 8   ALLERGY                3000 non-null   object
 9   WHEEZING               3000 non-null   object
 10  ALCOHOL_CONSUMING      3000 non-null   object
 11  COUGHING               3000 non-null   object
 12  SHORTNESS_OF_BREATH    3000 non-null   object
 13  SWALLOWING_DIFFICULTY  3000 non-null   object
 14  CHEST_PAIN             3000 non-null   object
 15  LUNG_CANCER            3000 non-null   object
dtypes: int64(1), object(15)
memory usage: 375.1+ KB

In [6]:
data.shape

(3000, 16)

In [7]:
data.value_counts(dropna = False)

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC_DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL_CONSUMING  COUGHING  SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  LUNG_CANCER
M       53   Yes      No              No       No             No               Yes      Yes      Yes       Yes                No        No                   Yes                    No          NO             2
        50   Yes      Yes             Yes      No             Yes              No       Yes      No        No                 No        No                   Yes                    No          YES            2
F       30   No       No              No       No             Yes              Yes      No       No        No                 No        Yes                  Yes                    Yes         NO             1
M       47   No       Yes             Yes      Yes            No               No       No       No        Yes                No        No                   Yes                    No          NO             1
                      No              Yes      Yes            Yes              Yes      Yes      No        No                 No        Yes                  Yes                    No          NO             1
                                                                                                                                                                                                              ..
F       63   Yes      Yes             No       Yes            No               Yes      Yes      No        No                 No        Yes                  Yes                    Yes         NO             1
                                                              Yes              Yes      No       Yes       Yes                Yes       Yes                  Yes                    No          NO             1
                                                                                        Yes      No        No                 No        No                   No                     No          YES            1
                                                                                                                              Yes       No                   Yes                    Yes         YES            1
M       80   Yes      Yes             Yes      Yes            No               Yes      No       Yes       Yes                Yes       Yes                  Yes                    No          NO             1
Name: count, Length: 2998, dtype: int64

In [8]:
data.dropna(axis=1)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,Yes,Yes,Yes,No,No,Yes,No,No,No,No,No,No,Yes,NO
1,F,55,Yes,No,No,Yes,Yes,No,No,No,Yes,Yes,Yes,No,No,NO
2,F,78,No,No,Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,Yes,Yes,YES
3,M,60,No,Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,Yes,No,No,YES
4,F,80,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes,Yes,Yes,No,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,F,71,No,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,Yes,Yes,No,NO
2996,F,75,Yes,No,Yes,Yes,Yes,No,No,No,No,Yes,Yes,No,Yes,NO
2997,F,62,No,No,No,Yes,No,No,No,No,Yes,Yes,No,No,No,YES
2998,M,30,Yes,Yes,No,No,No,No,No,No,No,Yes,No,Yes,No,YES
2999,M,40,Yes,No,No,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes,Yes,YES